// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IBufferPool
 * @notice Interface for BufferPool contract
 */
interface IBufferPool {
    /// @notice Parameters for local onramp (Fiat24 token -> USDC)
    struct OnrampParams {
        address user;
        address tokenIn;
        uint256 amountIn;
        uint256 minAmountOut;
        uint256 feeAmount;
    }

    /// @notice Parameters for cross-chain onramp (Fiat24 token -> USDC -> bridge -> destination swap)
    struct CrossChainOnrampParams {
        address user;
        address tokenIn;            // Fiat24 token
        uint256 amountIn;
        uint256 minAmountOut;       // Minimum USDC after FX conversion
        uint256 feeAmount;          // Fee amount in USDC to send to feeReceiver (on source chain)
        uint32 dstEid;              // Destination chain endpoint ID
        address dstAggregator;      // Aggregator on destination chain
        address dstTokenOut;        // Target token on destination chain
        address dstReceiver;        // Final receiver on destination chain
        bytes dstSwapCalldata;      // Generated by frontend/backend via 1inch/Odos
        uint256 dstMinAmountOut;    // Minimum output on destination chain
        uint128 dstGasLimit;        // Gas limit for compose call
        uint256 bridgeMinAmount;    // Minimum USDC to receive on bridge (slippage)
    }

    /// @notice Parameters for swapUsdcToToken
    struct SwapParams {
        uint256 usdcAmount;
        uint256 feeAmount;
        address tokenOut;
        uint256 minAmountOut;
        address aggregator;
        bytes swapCalldata;
    }

    /// @notice EIP-2612 permit signature parameters
    struct PermitParams {
        uint256 deadline;
        uint8 v;
        bytes32 r;
        bytes32 s;
    }

    // View functions
    function getQuote(address tokenIn, uint256 amountIn) external view returns (uint256 usdcOut);

    // Onramp functions
    function onramp(OnrampParams calldata params) external;
    function permitAndOnramp(OnrampParams calldata params, PermitParams calldata permit) external;
    
    // Onramp and swap functions
    function onrampAndSwap(OnrampParams calldata onrampParams, SwapParams calldata swapParams) external;
    function permitAndOnrampAndSwap(
        OnrampParams calldata onrampParams,
        PermitParams calldata onrampPermit,
        SwapParams calldata swapParams
    ) external;

    // Swap functions
    function swapUsdcToToken(SwapParams calldata params) external;
    function permitAndSwapUsdcToToken(SwapParams calldata params, PermitParams calldata permit) external;

    // Cross-chain functions
    function onrampAndBridge(CrossChainOnrampParams calldata params) external payable;
    function permitAndOnrampAndBridge(CrossChainOnrampParams calldata params, PermitParams calldata permit) external payable;
    function quoteCrossChainFee(CrossChainOnrampParams calldata params, uint256 usdcOut) external view returns (uint256 nativeFee, uint256 minAmountLD);
}

